#!/usr/bin/env python3
"""Reproducibility and theory-alignment test for learned fixed-support tables.

CPU only.  No checkpoint, no GPU.

Given two or more realised allocation tables produced by independent training
runs that differ only in data order, this answers three separate questions that
a single run cannot:

1.  **Is the learned displacement reproducible?**  Cosine between the runs'
    normalised-coordinate displacements.
2.  **Does it agree with the closed-form construction?**  Cosine against the
    anchored EVQ-Cosh direction at the same support.
3.  **Is either number larger than drift would give?**  Both are compared
    against a simulated null.  Because `z` is a cumulative sum of softmax gaps
    with both endpoints pinned, an undirected walk in gap-logit space produces
    a *pinned* displacement whose cosines are strongly biased away from zero;
    testing against `0` instead of against this null is what makes a smooth
    single-humped displacement curve look meaningful when it is not.

The null is the honest version of the "it is only a random walk" claim: it can
confirm that claim, and it can refute it.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.lib.rope.schedules import evq_cosh_phi, geometric_inv_freq  # noqa: E402

torch.set_default_dtype(torch.float64)
STATUS = "LEARNED_ALLOCATION_DIRECTION_COMPARISON_V1"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tables", type=Path, nargs="+", required=True)
    parser.add_argument("--labels", nargs="+")
    parser.add_argument("--pair-count", type=int, default=64)
    parser.add_argument("--base", type=float, default=500_000.0)
    parser.add_argument("--tau", type=float, default=4.0)
    parser.add_argument("--null-samples", type=int, default=20_000)
    parser.add_argument("--null-seed", type=int, default=20_260_826)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def displacement(table: np.ndarray, native: torch.Tensor) -> torch.Tensor:
    x_native = -native.log()
    span = x_native[-1] - x_native[0]
    z = (-torch.as_tensor(table, dtype=torch.float64).log() - x_native[0]) / span
    return z - (x_native - x_native[0]) / span


def cosine(a: torch.Tensor, b: torch.Tensor) -> float:
    denominator = float(a.norm()) * float(b.norm())
    return float(a @ b) / denominator if denominator > 0 else float("nan")


def pinned_walk_null(
    pairs: int, samples: int, seed: int, reference: torch.Tensor
) -> dict[str, float]:
    """Cosines between displacements generated by undirected gap-logit noise."""

    generator = torch.Generator().manual_seed(int(seed))
    uniform_gap_log = float(np.log(1.0 / (pairs - 1)))
    pair_cosines = np.empty(samples, dtype=np.float64)
    reference_cosines = np.empty(samples, dtype=np.float64)
    z_native = torch.linspace(0.0, 1.0, pairs, dtype=torch.float64)
    for index in range(samples):
        draws = []
        for _ in range(2):
            noise = torch.randn(pairs - 1, generator=generator, dtype=torch.float64)
            gaps = torch.softmax(uniform_gap_log + noise, dim=0)
            z = torch.cat((torch.zeros(1, dtype=torch.float64), torch.cumsum(gaps, 0)))
            draws.append(z - z_native)
        pair_cosines[index] = cosine(draws[0], draws[1])
        reference_cosines[index] = cosine(draws[0], reference)
    return {
        "pairwise_mean": float(pair_cosines.mean()),
        "pairwise_p95": float(np.quantile(pair_cosines, 0.95)),
        "pairwise_p99": float(np.quantile(pair_cosines, 0.99)),
        "vs_reference_mean": float(reference_cosines.mean()),
        "vs_reference_p95": float(np.quantile(reference_cosines, 0.95)),
        "vs_reference_p99": float(np.quantile(reference_cosines, 0.99)),
        "samples": int(samples),
    }


def main() -> int:
    args = parse_args()
    pairs = int(args.pair_count)
    native = geometric_inv_freq(head_dim=2 * pairs, base=float(args.base))
    phi = evq_cosh_phi(pairs, tau=float(args.tau), midpoint=True)
    z_cosh = (phi - phi[0]) / (phi[-1] - phi[0])
    reference = z_cosh - torch.linspace(0.0, 1.0, pairs, dtype=torch.float64)

    labels = list(args.labels) if args.labels else [p.parent.name or p.stem for p in args.tables]
    if len(labels) != len(args.tables):
        raise ValueError("labels and tables must have the same length")

    moves: list[torch.Tensor] = []
    entries = []
    for label, path in zip(labels, args.tables):
        table = np.load(path.resolve(), allow_pickle=False)
        if table.shape != (pairs,) or not np.all(table[:-1] > table[1:]):
            raise RuntimeError(f"{label}: table is not a strictly decreasing {pairs}-vector")
        move = displacement(table, native)
        moves.append(move)
        entries.append(
            {
                "label": label,
                "path": str(path.resolve()),
                "table_file_sha256": sha256_file(path.resolve()),
                "displacement_norm": float(move.norm()),
                "max_abs_coordinate_shift": float(move.abs().max()),
                "cosine_with_anchored_cosh": cosine(move, reference),
                "displacement_norm_ratio_to_anchored_cosh": float(move.norm() / reference.norm()),
            }
        )

    pairwise = [
        {
            "a": labels[i],
            "b": labels[j],
            "cosine": cosine(moves[i], moves[j]),
            "norm_ratio": float(moves[i].norm() / moves[j].norm()),
        }
        for i in range(len(moves))
        for j in range(i + 1, len(moves))
    ]

    null = pinned_walk_null(pairs, int(args.null_samples), int(args.null_seed), reference)
    report = {
        "status": STATUS,
        "pair_count": pairs,
        "base": float(args.base),
        "tau": float(args.tau),
        "script_sha256": sha256_file(Path(__file__).resolve()),
        "tables": entries,
        "pairwise_between_runs": pairwise,
        "pinned_walk_null": null,
        "verdict_rules": {
            "reproducible_direction": (
                "every pairwise cosine exceeds the null pairwise p99"
            ),
            "theory_aligned": (
                "every cosine_with_anchored_cosh exceeds the null vs_reference p99"
            ),
            "drift_only": (
                "pairwise cosines fall inside the null pairwise distribution"
            ),
        },
    }
    args.output.resolve().parent.mkdir(parents=True, exist_ok=True)
    args.output.resolve().write_text(
        json.dumps(report, indent=2, sort_keys=True), encoding="utf-8"
    )

    print("null: pairwise mean %.4f p99 %.4f | vs-EVQ mean %.4f p99 %.4f" % (
        null["pairwise_mean"], null["pairwise_p99"],
        null["vs_reference_mean"], null["vs_reference_p99"]))
    for entry in entries:
        print("%-28s |dz|=%.5f  cos_EVQ=%+.4f  ratio=%.5f" % (
            entry["label"], entry["displacement_norm"],
            entry["cosine_with_anchored_cosh"],
            entry["displacement_norm_ratio_to_anchored_cosh"]))
    for item in pairwise:
        print("pairwise %-16s %-16s cos=%+.4f" % (item["a"], item["b"], item["cosine"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
